export const P2PTRADE_FETCH = 'p2pTrade/FETCH';
export const P2PTRADE_DATA  = 'p2pTrade/DATA';
export const P2PTRADE_ERROR = 'p2pTrade/ERROR';

export const P2PTRADE_APPROVE_FETCH = 'p2pTrade/APPROVE_FETCH';
export const P2PTRADE_APPROVE_DATA = 'p2pTrade/APPROVE_DATA';
export const P2PTRADE_APPROVE_ERROR = 'p2pTrade/APPROVE_ERROR';

export const P2PTRADE_CANCEL_FETCH = 'p2pTrade/CANCEL_FETCH';
export const P2PTRADE_CANCEL_DATA = 'p2pTrade/CANCEL_DATA';
export const P2PTRADE_CANCEL_ERROR = 'p2pTrade/CANCEL_ERROR';

export const P2PTRADE_FEEDBACK_FETCH = 'p2pTrade/FEEDBACK_FETCH';
export const P2PTRADE_FEEDBACK_DATA = 'p2pTrade/FEEDBACK_DATA';
export const P2PTRADE_FEEDBACK_ERROR = 'p2pTrade/FEEDBACK_ERROR';

export const P2PTRADE_COMPLAIN_FETCH = 'p2pTrade/COMPLAIN_FETCH';
export const P2PTRADE_COMPLAIN_DATA = 'p2pTrade/COMPLAIN_DATA';
export const P2PTRADE_COMPLAIN_ERROR = 'p2pTrade/COMPLAIN_ERROR';

export const P2PTRADE_UPDATE_EMIT = 'p2pTrade/UPDATE_EMIT';
export const P2PTRADE_UPDATE_FINISH = 'p2pTrade/UPDATE_FINISH';

export const P2PTRADE_CREATE_FETCH = 'p2pTrade/CREATE_FETCH';
export const P2PTRADE_CREATE_FINISH = 'p2pTrade/CREATE_FINISH';
export const P2PTRADE_CREATE_HANDLE_FINISH = 'p2pTrade/CREATE_HANDLE_FINISH';